enhance services
TremblingV5/DouTok pull request #136
Opened 2024-03-09 11:34 UTC by AbigailJixiangyuyu

## Link to an issue

## What
1. 返回类型为 `int64` 的编码为 `string` ， 没有修改完全
2. 添加了 `login` 的API文档
3. `token` 在登录接口中，设置到 `cookie` 中，后续无需主动设置和传递
4. 解决了 `relation` 服务没有连接其余服务客户端，导致空指针异常的问题
5. 修复了一些由于空指针导致的报错（但代码不够优雅），偶尔还是要报错，不清楚原因
6. 完成上传视频上传到 `MinIO` 中
7. 添加了 `quickstart.md`

## How

## Screenshots

## How to test

## Checklist

- [ ] Link to an issue if it really related.
- [ ] At least describe what this PR does.
- [ ] Use `rebase` to confirm that current branch doesn't conflict with main branch.
- [ ] Unit tests. At least do not reduce the unit test coverage.
- [ ] Checked and updated `guidelines.md` which used to describe how to build, deploy and use DouTok.

2024-03-09 14:14 UTC, TremblingV5 requested changes
很棒的改动！

只有一些比较小的建议，没有什么大问题。

另外，建议之后在搞其他东西的时候可以多分几个PR出来。这个PR的7个点更建议分成7个PR提交（7个点之间的互相关联性感觉也不大）。这样有两个好处：

1. Review的时候更好理解更方便些
2. Git History会更整洁一些。当前PR合并以后，Git History上只会留下一个`enhance services`，后面去看Git History，很难直接看出来这个PR做了什么。而将这个PR划分成7个，每个都有相对更具体地描述，也更方便看到一个PR里去做了什么，更加方便后续的更改

拆分开确实可能更麻烦一些，但是相对更标准更规范，当前PR就这个样子吧，省的麻烦了

2024-03-09 14:14 UTC, TremblingV5 commented on docs-site/docs/quickstart.md
> +#### RPC服务
nit: 这里感觉可以给`RPC服务`换个名字。

现在的这个稀碎的服务划分是我从网上看来的一个划分方式：

1. API业务网关
2. 逻辑层（除API模块外，所有不带有`Domain`的模块，相当于单体项目的controller + service层）
3. 业务层（所有`xxxDomain`模块，相当于单体项目的service + repo层）

2024-03-09 14:14 UTC, TremblingV5 commented on docs-site/docs/quickstart.md
> +http://localhost:8088/swagger/index.html
Markdown提供了专门的网址格式

2024-03-09 14:14 UTC, TremblingV5 commented on pkg/hbaseHandle/put.go
> -
nit: 一般来说，一个代码块结束后应该有一空行

2024-03-09 14:15 UTC, TremblingV5 commented on applications/videoDomain/service/publish_action.go
> +	go SaveVideo2HB(id, uint64(user_id), title, play_url, cover_url, fmt.Sprint(timestamp))
另外，估计是HBase没有配置对。可以留一下操作系统和Docker版本信息。

2024-03-09 14:16 UTC, TremblingV5 commented
另外，第5点提到`修复了一些由于空指针导致的报错（但代码不够优雅），偶尔还是要报错，不清楚原因`

如果方便的话可以把堆栈信息贴以下

2024-03-10 03:56 UTC, AbigailJixiangyuyu commented on applications/videoDomain/service/publish_action.go
> +	go SaveVideo2HB(id, uint64(user_id), title, play_url, cover_url, fmt.Sprint(timestamp))
解决了

2024-03-10 04:12 UTC, AbigailJixiangyuyu commented
```
2024/03/10 12:09:40.516625 default_server_handler.go:223: [Error] KITEX: processing request error, remote
Service=DouTokUserServer, remoteAddr=127.0.0.1:64593, error=biz error: remote or network error: default c
odec read failed: read tcp 127.0.0.1:64573->127.0.0.1:8100: wsarecv: An established connection was aborte
d by the software in your host machine.
```
我这边经常报这个错，但我不清楚是不是因为 `windows` 上没有使用 `netpoll` 的原因
业务逻辑是没问题的，在什么代码都不改变的情况下，有时能正确返回结果，有时报上面的错

2024-03-10 04:17 UTC, AbigailJixiangyuyu commented on docs-site/docs/quickstart.md
> +```
这个你检查下我修改之后的内容，我不知道理解对你的意思没

2024-03-10 04:19 UTC, TremblingV5 commented
> ```
> 2024/03/10 12:09:40.516625 default_server_handler.go:223: [Error] KITEX: processing request error, remote
> Service=DouTokUserServer, remoteAddr=127.0.0.1:64593, error=biz error: remote or network error: default c
> odec read failed: read tcp 127.0.0.1:64573->127.0.0.1:8100: wsarecv: An established connection was aborte
> d by the software in your host machine.
> ```
> 
> 我这边经常报这个错，但我不清楚是不是因为 `windows` 上没有使用 `netpoll` 的原因 业务逻辑是没问题的，在什么代码都不改变的情况下，有时能正确返回结果，有时报上面的错

这个报错直接看的话是因为那个连接被主动关闭了，应该是和windows的netpoll有关系，另外为了适配windows那里我看options也有一些改动，可能是超时或者啥原因把连接关闭了，不是什么大问题

2024-03-10 04:20 UTC, AbigailJixiangyuyu commented on config/configStruct/hbase.go
这里修改后才能正确读取到配置，之前没注意到这里代码是写错的

2024-03-10 04:25 UTC, TremblingV5 commented on docs-site/docs/quickstart.md
> +```
这里俺的意思是这样的：
![image](https://github.com/TremblingV5/DouTok/assets/43563921/ab3ef423-4487-4da6-8107-60762ecd1735)
这个数据Markdown代码块的一个要求

2024-03-10 09:33 UTC, TremblingV5 approved these changes

2024-03-10 09:33 UTC, merged