Enhance service operation
TremblingV5/DouTok pull request #139
Opened 2024-03-11 13:59 UTC by AbigailJixiangyuyu

## Link to an issue

## What
- 解决了 `CommentDomain`  没有 初始化 `InitSnowFlake` 导致的空指针
- 解决了 `Favorite` 没有初始化 `errs` 导致的空指针
- 移除了 `api.proto` 中无用的 `token` 参数
- 返回前端的 `int64` 类型转为 `string` 

## How

## Screenshots

## How to test

## Checklist

- [ ] Link to an issue if it really related.
- [x] At least describe what this PR does.
- [x] Use `rebase` to confirm that current branch doesn't conflict with main branch.
- [ ] Unit tests. At least do not reduce the unit test coverage.
- [ ] Checked and updated `guidelines.md` which used to describe how to build, deploy and use DouTok.

2024-03-11 16:06 UTC, TremblingV5 requested changes
## Comment Domain重构问题

Comment Domain是我之前已经重构过的一个模块，建议这部分改动可以提issue或者discussion说一下具体想法，然后再看怎样落实

## Token相关

当前DouTok还没有独立的前端，所以希望还是能保持和字节提供的客户端的兼容性

## user_id解析

建议依然保留从`token`中解析`user_id`的方式，并在设置`user_id`到上下文中时直接设置成`int64`类型，毕竟go的代码里的处理均是针对int64的

## 其他

还是建议不同的功能尽可能分到多个PR里去

2024-03-12 01:58 UTC, AbigailJixiangyuyu commented on applications/commentDomain/service/typedef.go
> +type CommentDomainUtil struct {
这个是因为之前的命名会导致两个不同的结构体使用相同的名字，然后使用上就出错了。就是上面提到的snakeflake的空指针异常

2024-03-12 01:59 UTC, AbigailJixiangyuyu commented on proto/api.proto
> +  int64 like_count = 5 [(api.body) = "id,string"]; // 该评论点赞数
我的错

2024-03-12 02:01 UTC, AbigailJixiangyuyu commented on applications/commentDomain/service/service.go
> +	DomainUtil             *CommentDomainUtil
这部分就是因为OOP导致业务逻辑都出错了，得仔细看看是怎样的逻辑

2024-03-12 02:23 UTC, AbigailJixiangyuyu commented on applications/commentDomain/main.go
> +// TODO 整个 CommentDomain 需要重构，代码结构和其他服务相比很不协调
由`service.NewCommentDomainService`生成的结构体，和`handler.NewCommentDomainHandler`接收的结构体就不是一个东西，由于`handler.NewCommentDomainHandler`使用到了接口，导致上面使用到的传入的参数是无效的。

2024-03-12 02:25 UTC, AbigailJixiangyuyu commented on applications/commentDomain/handler/add_comment.go
> -	result, err := s.service.AddComment(ctx, req.VideoId, req.UserId, utils.GetSnowFlakeId().Int64(), 0, 0, req.CommentText)
其实主要问题是这里，调用`utils.GetSnowFlakeId()`会导致空指针异常，因为初始化的`snowflake`并没有保存在这里，而是其他地方

2024-03-12 02:26 UTC, AbigailJixiangyuyu commented on applications/commentDomain/handler/add_comment.go
> +	result, err := service.DomainUtil.AddComment(ctx, req.VideoId, req.UserId, service.DomainUtil.SnowflakeHandle.GetId().Int64(), 0, 0, req.CommentText)
实际上是在这里，所以我才把`SnowflakeHandle`这些字段改为大写，让外部可以调用到

2024-03-12 02:43 UTC, TremblingV5 commented on applications/commentDomain/service/typedef.go
> +type CommentDomainUtil struct {
如果相同名称的结构体不在同一个命名空间下，根据命名空间控制就可以了

2024-03-12 02:43 UTC, TremblingV5 commented on applications/commentDomain/service/service.go
> +	DomainUtil             *CommentDomainUtil
业务逻辑出错是指snowflake的空指针吗

2024-03-12 02:45 UTC, TremblingV5 commented on applications/commentDomain/handler/add_comment.go
> -	result, err := s.service.AddComment(ctx, req.VideoId, req.UserId, utils.GetSnowFlakeId().Int64(), 0, 0, req.CommentText)
原本Service结构体里有一个SnowFlake的Handler，用那个应该就可以了。

2024-03-12 02:46 UTC, TremblingV5 commented on applications/commentDomain/handler/add_comment.go
> +	result, err := service.DomainUtil.AddComment(ctx, req.VideoId, req.UserId, service.DomainUtil.SnowflakeHandle.GetId().Int64(), 0, 0, req.CommentText)
这里可以看两种情况

1. Snowflake给出的ID一定要handler控制，将snowflake handler上移给handler
2. 如果不需要，则减少`AddComment`的参数，在service内部去给出一个snowflake id

2024-03-12 03:22 UTC, AbigailJixiangyuyu commented on applications/commentDomain/handler/add_comment.go
> -	result, err := s.service.AddComment(ctx, req.VideoId, req.UserId, utils.GetSnowFlakeId().Int64(), 0, 0, req.CommentText)
但是由于使用了接口无法调用到

2024-03-12 03:25 UTC, AbigailJixiangyuyu commented on applications/commentDomain/handler/add_comment.go
> -	result, err := s.service.AddComment(ctx, req.VideoId, req.UserId, utils.GetSnowFlakeId().Int64(), 0, 0, req.CommentText)
![image](https://github.com/TremblingV5/DouTok/assets/129409676/71fe8b78-6ae8-42f6-85e3-dbf202ef809d)
这里是通过这个接口接收的，导致无法使用原本Service里的内容

2024-03-12 03:39 UTC, AbigailJixiangyuyu commented on applications/api/biz/handler/api/comment_service.go
> +	userId, err := strconv.ParseInt(c.Keys["user_id"].(string), 10, 64)
![image](https://github.com/TremblingV5/DouTok/assets/129409676/2f584e70-c2a4-4d71-b914-4928cef3cef3)
项目中身份校验的部分使用到了 `github.com/hertz-contrib/jwt` 这个包，在包内部实现了改功能

2024-03-12 03:39 UTC, AbigailJixiangyuyu commented on applications/api/biz/handler/api/comment_service.go
> +	userId, err := strconv.ParseInt(c.Keys["user_id"].(string), 10, 64)
这个包是项目中本来就使用到的，不是我加的

2024-03-12 04:30 UTC, AbigailJixiangyuyu commented
commentDomain我还原回去了，换个个方案来处理 `utils.GetSnowFlakeId()` 导致的空指针异常

2024-03-12 11:31 UTC, AbigailJixiangyuyu commented on applications/api/biz/handler/api/comment_service.go
> +	videoId, err := strconv.ParseInt(req.VideoId, 10, 64)
前端传过来的不用，我改下，我也觉得很难处理，js里面没有int64类型，都是用float保存了，我也不知道怎么处理好一些

2024-03-12 11:42 UTC, AbigailJixiangyuyu commented
err.config 那部分只是为了先让他不报错，不然有空指针

2024-04-10 03:57 UTC, closed without merging