Fav dev
TremblingV5/DouTok pull request #21
Opened 2023-01-31 03:14 UTC by IsJulia

修改了application/favorite/dal下的代码，以及在application/favorite下加了个README.md

2023-01-31 03:31 UTC, BaiZe1998 commented on config/mysql.yaml.orig
> +<<<<<<< HEAD
need to remove residual traces of merge, such as "<<<<<<<< HEAD"

unmodified documents do not need to be submitted

2023-01-31 03:31 UTC, BaiZe1998 commented on config/mysql.yaml.orig
> +host: "127.0.0.1"
why did you submit the .orig file?

2023-01-31 03:31 UTC, BaiZe1998 commented on deploy/env.yml.orig
> +=======
need to remove residual traces of merge, such as "<<<<<<<< HEAD"

unmodified documents do not need to be submitted

2023-01-31 03:31 UTC, BaiZe1998 commented on deploy/hbase/hbase-site.xml.orig
> +<<<<<<< HEAD
need to remove residual traces of merge, such as "<<<<<<<< HEAD"

unmodified documents do not need to be submitted

2023-01-31 03:31 UTC, BaiZe1998 commented on pkg/errno/errno.go
>  	BadRequest             = NewErrNo(BadRequestErrCode, "Request Failed")
need to remove residual traces of merge, such as "<<<<<<<< HEAD"

unmodified documents do not need to be submitted

2023-01-31 13:10 UTC, TremblingV5 commented on applications/favorite/README.md
> +- 关于涉及到video和user的部分，还有待进一步协商。
favorite模块下的video表不必是一张完整的video表，在知道video id的情况下，维护user对video的喜欢关系和video的喜欢数量即可

2023-01-31 13:19 UTC, TremblingV5 requested changes
# 主要包括两个问题

## 文件名问题

有的文件添加了一个".orig"的后缀，这个后缀的文件是否有特殊含义，我看到诸如`go.mod`和`kitex_gen/user/user.pb.go`这样的文件都添加了这样的后缀，故我猜测这个后缀应该是不小心加上的吧？

## 冲突解决残留的问题

git判断代码中存在冲突时，会留下`<<<<<<HEAD`和`========`以及`>>>>>>>sha code`等格式的记号，分别代表传入分支的代码和当前分支的代码，具体可以通过搜索引擎进行了解。但是要合并代码时，必须将这些标记给删除掉，否则这些标记将会直接影响代码的运行

2023-01-31 13:21 UTC, TremblingV5 commented on deploy/env.yml.orig
> +version: "3"
此文件存在orig后缀的问题

2023-01-31 13:24 UTC, TremblingV5 reviewed
标注出了需要解决问题的具体位置

2023-01-31 13:24 UTC, TremblingV5 commented on deploy/env.yml.orig
> +version: "3"
此文件存在orig后缀的问题

2023-01-31 13:24 UTC, TremblingV5 commented on pkg/errno/errno.go.orig
> +package errno
此文件存在orig后缀的问题

2023-01-31 13:24 UTC, TremblingV5 commented on go.mod.orig
> +module github.com/TremblingV5/DouTok
此文件存在orig后缀的问题

2023-01-31 13:24 UTC, TremblingV5 commented on deploy/env.yml.orig
> +=======
此处存在1处冲突合并残留，需要解决

2023-01-31 13:24 UTC, TremblingV5 commented on go.mod.orig
> +>>>>>>> 88e4d588ab0e357b17e19dccbeda7cf64e8244af
此文件存在7处冲突合并残留，需要解决

2023-01-31 13:24 UTC, TremblingV5 commented on pkg/errno/errno.go.orig
> +<<<<<<< HEAD
此处存在1处冲突合并残留，需要解决

2023-02-01 01:46 UTC, IsJulia commented on applications/favorite/README.md
> +- 关于涉及到video和user的部分，还有待进一步协商。
好的

2023-02-02 13:49 UTC, TremblingV5 commented on applications/favorite/dal/model/video.go
> +type Video struct {
此处Video表可以是一张不完整的Video表，只需要维护喜欢数量即可，另外还需要一张记录具体的喜欢关系的表

2023-02-02 13:49 UTC, TremblingV5 commented on applications/favorite/dal/query/favorite.go
> +	if err := DB.WithContext(ctx).First(user, uid).Error; err != nil {
这里的DB是未定义的变量，需要通过一个init函数来完成对DB的初始化，然后才能进行查询

2023-02-02 13:49 UTC, TremblingV5 commented on applications/favorite/dal/query/favorite.go
> +func GetFavoriteRelation(ctx context.Context, uid int64, vid int64) (*Video, error) {
Video变量需要具体地引用到

2023-02-02 13:49 UTC, TremblingV5 commented on applications/favorite/dal/query/favorite.go
> +			return errno.ErrDatabase
这个错误貌似是未定义地

2023-02-02 13:49 UTC, TremblingV5 commented on applications/favorite/dal/query/favorite.go
> +		user := new(User)
这里没有必要创建一整个User对象，只知道user_id和video_id就可以创建一个user对video的喜欢关系，user和video除了各自的id外，其他的数据项并不是这个模块所关心的内容。

例如创建一张favorite表，包含主要字段：user_id,video_id,status 即可，这样就可以做到记录下user和video的喜欢关系。

多余的数据信息可以通过rpc调用其他微服务模块来获取

2023-02-02 13:49 UTC, TremblingV5 commented on applications/favorite/service/list.go
> +	FavoriteVideos, err := db.FavoriteList(s.ctx, req.UserId)
这个函数内的两个函数都还没有具体实现，需要实现这两个函数，operation.go类似

2023-02-03 03:29 UTC, IsJulia commented on applications/favorite/dal/model/video.go
> +type Video struct {
好的！

2023-02-03 03:29 UTC, IsJulia commented on applications/favorite/dal/query/favorite.go
> +	if err := DB.WithContext(ctx).First(user, uid).Error; err != nil {
好的！

2023-02-03 03:30 UTC, IsJulia commented on applications/favorite/dal/query/favorite.go
> +func GetFavoriteRelation(ctx context.Context, uid int64, vid int64) (*Video, error) {
好的！

2023-02-03 03:30 UTC, IsJulia commented on applications/favorite/dal/query/favorite.go
> +			return errno.ErrDatabase
噢噢好的

2023-02-03 03:31 UTC, IsJulia commented on applications/favorite/dal/query/favorite.go
> +		user := new(User)
好的！

2023-02-03 03:31 UTC, IsJulia commented on applications/favorite/service/list.go
> +	FavoriteVideos, err := db.FavoriteList(s.ctx, req.UserId)
好的！

2023-02-06 15:09 UTC, TremblingV5 commented on applications/favorite/service/favorite_action.go
> +	if op == true {
此处可能需要添加一个对已存在的status的查询，如果要更改的status与已经存在的status相同，此时就不应该更改喜欢数

可能由于网络波动等情况，导致用户连续发出了“喜欢”操作，如果没有这个逻辑，可能会导致某视频只增加了一个喜欢用户，但是VideoCount表中却增加了多个喜欢数

2023-02-07 11:35 UTC, IsJulia commented on applications/favorite/service/favorite_action.go
> +	if op == true {
噢噢好的！

2023-04-25 13:52 UTC, closed without merging